spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - http://localhost:5173
              - http://localhost:3000
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
