server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: product
    password: pass
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: caffeine
    cache-names: productById,productPage
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=5m,recordStats
