server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sellerdb
    username: seller
    password: pass
    hikari:
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,prometheus
